In [1]:
import numpy as np

In [2]:
u = np.array([3, 4])
w = np.array([9, 6])

In [4]:
u + w, w + u

(array([12, 10]), array([12, 10]))

In [8]:
3*u - 2*w

array([-9,  0])

In [12]:
((u[0] ** 2) + (u[1] ** 2)) ** 0.5

5.0

In [15]:
(u ** 2).sum() ** 0.5

5.0

In [16]:
np.linalg.norm(u)

5.0

In [18]:
u * (1/5)

array([0.6, 0.8])

In [20]:
np.linalg.norm(u/5)

1.0

In [21]:
a = np.array([2,7])
b = np.array([3,4])

In [22]:
a.dot(b)

34

In [23]:
b.dot(a)

34

In [24]:
a @ b

34

In [31]:
inv = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
inv

0.9340518348510853

In [32]:
np.degrees(np.arccos(inv))

20.92450174492117

In [35]:
np.array([[1,7],[2,4]]) @ np.array([[3,3],[5,2]])

array([[38, 17],
       [26, 14]])

# Warning ... about to explode!

In [37]:
X = np.array([[2,6,8], [3,1,4], [4,1,5]])

In [38]:
X.T

array([[2, 3, 4],
       [6, 1, 1],
       [8, 4, 5]])

In [39]:
np.linalg.inv(X)

array([[-6.55069037e+15,  1.44115188e+17, -1.04811046e+17],
       [-6.55069037e+15,  1.44115188e+17, -1.04811046e+17],
       [ 6.55069037e+15, -1.44115188e+17,  1.04811046e+17]])

In [41]:
np.linalg.matrix_rank(X)

2

In [43]:
X = np.array([[2,6], [3,1]])
X

array([[2, 6],
       [3, 1]])

In [44]:
np.linalg.matrix_rank(X)

2

In [46]:
np.linalg.inv(X) @ X

array([[1., 0.],
       [0., 1.]])